[tool.poetry]
name = "my-flask-on-oracle-cloud"
version = "0.1.0"
description = ""
authors = ["bosbyj <bosbyj@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.8"
pymongo = "3.11.1"
dnspython = "2.0.0"
Flask-PyMongo = "2.3.0"
Flask = "1.1.2"
Flask-Login = "0.5.0"
jieba = "0.42.1"
pydantic = "1.5.1"
pytest = "5.4.2"
sqlitefts = "0.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
